seed: 1004
num_gpus: 1
trainer:
  _class: ImgClassifierTrainer
  seed: 42
  eval_seed: 0
  train_epochs: 3
  valid_freq_epoch: 1
  log_freq_step: 10
  pmap: True
  debug: False
  pbar: True
  tabulate_model: True
  tabulate_param: True
  log_grad_norm: True
  detect_nans: True
  restore_best: True
  donate_state: True
  logger:
    _class: jax_trainer.logger.Logger
    log_dir: tests/checkpoints/BuildTrainerTest/
    tool: TensorBoard
    project_name: default
    verbosity: warning
    stderrthreshold: warning

    infer_with_name: False
  callbacks:
    ModelCheckpoint:
      monitor: valid/acc
      mode: max
      save_top_k: 1
      save_opt_state: False
    ConfusionMatrixCallback:
      normalize: True
      cmap: Blues
      freq_epoch: 2
    LearningRateMonitor:
      freq_epoch: 1
model:
  _class: jax_trainer.examples.network.SimpleNetwork
  hparams:
    hidden_size: 32
    num_classes: 10
    batch_norm: True
optimizer:
  builder: jax_trainer.optimizer.OptimizerBuilder
  lr: 1e-3
  optim:
    _class: adam
    params:
      b1: 0.9
      b2: 0.999
  transforms:
    pre:
      grad_clip_norm: 10.0
    post:
      weight_decay: 0
    # grad_clip_value: 0.1
  scheduler:
    name: warmup_cosine_decay
    params:
      warmup_steps: 100
dataset:
  _class: jax_trainer.datasets.examples.build_cifar10_datasets
  data_dir: ~/Datasets/
  batch_size: 128
  num_workers: 0
